"""link orders to contracts

Revision ID: 28cccd78d28f
Revises: 3ff421f34990
Create Date: 2026-08-19 12:24:12.357584
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '28cccd78d28f'
down_revision: str | None = '3ff421f34990'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('contract_id', mysql.BIGINT(unsigned=True), nullable=False))
    op.create_index('idx_orders_contract_id', 'orders', ['contract_id'], unique=False)
    op.create_foreign_key('fk_orders_contract', 'orders', 'contracts', ['contract_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.alter_column('products', 'stock',
               existing_type=mysql.DECIMAL(precision=12, scale=3),
               server_default=sa.text('0'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'stock',
               existing_type=mysql.DECIMAL(precision=12, scale=3),
               server_default=sa.text("'0.000'"),
               existing_nullable=False)
    op.drop_constraint('fk_orders_contract', 'orders', type_='foreignkey')
    op.drop_index('idx_orders_contract_id', table_name='orders')
    op.drop_column('orders', 'contract_id')
    # ### end Alembic commands ###
